# refle developer tasks. Run `make help` for the list.
SHELL := /bin/bash
export PATH := $(HOME)/.local/bin:$(PATH)

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Install JS and Python deps
	npm install
	uv sync --all-packages

.PHONY: up
up: ## Start the local infra stack (Postgres, Redis, MinIO)
	docker compose -f deploy/docker-compose.yml up -d

.PHONY: down
down: ## Stop the local infra stack
	docker compose -f deploy/docker-compose.yml down

.PHONY: migrate
migrate: ## Apply database migrations
	cd services/api && uv run --env-file ../../.env alembic upgrade head

.PHONY: revision
revision: ## Create a new autogenerated migration (msg="...")
	cd services/api && uv run --env-file ../../.env alembic revision --autogenerate -m "$(msg)"

.PHONY: api
api: ## Run the FastAPI dev server
	uv run uvicorn refle_api.main:app --reload --port 8000 --app-dir services/api

.PHONY: worker
worker: ## Run the Celery worker
	cd services/worker && uv run --env-file ../../.env celery -A refle_worker.celery_app worker -B --loglevel=info

.PHONY: web
web: ## Run the Next.js dev server
	npm run dev --workspace apps/web

.PHONY: seed
seed: ## Seed the SOC 2 control catalog
	uv run python -m refle_api.seed

.PHONY: openapi
openapi: ## Export the OpenAPI schema and regenerate the TS SDK types
	uv run python -c "import json; from refle_api.main import create_app; print(json.dumps(create_app().openapi(), indent=2))" > packages/sdk/openapi.json
	npm run generate --workspace packages/sdk

.PHONY: lint
lint: ## Lint Python + JS
	uv run ruff check .
	npm run lint

.PHONY: fmt
fmt: ## Format Python
	uv run ruff format .

.PHONY: test
test: ## Run Python tests
	uv run pytest

.PHONY: dev
dev: up ## Start infra then print next steps
	@echo ""
	@echo "Infra is up. In separate terminals run:"
	@echo "  make migrate   # once"
	@echo "  make api"
	@echo "  make web"
