"""enable pgvector extension

This stable, hand-written baseline enables pgvector (used by the embeddings table
for RAG). The schema migration for the domain tables is autogenerated on top of it.

Revision ID: 0001_pgvector
Revises:
Create Date: 2026-06-20
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001_pgvector"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
