"""add evidence and policies

Revision ID: 1517efc52ed6
Revises: 77143f58f3ca
Create Date: 2026-06-20 15:29:25.954775
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1517efc52ed6"
down_revision: str | None = "77143f58f3ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source", sa.Enum("manual", "integration", name="evidence_source"), nullable=False
        ),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_organization_id"), "evidence", ["organization_id"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug"),
    )
    op.create_index(
        op.f("ix_policies_organization_id"), "policies", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_policies_slug"), "policies", ["slug"], unique=False)
    op.create_table(
        "policy_versions",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "version"),
    )
    op.create_index(
        op.f("ix_policy_versions_policy_id"), "policy_versions", ["policy_id"], unique=False
    )
    op.create_table(
        "evidence_controls",
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("org_control_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_control_id"], ["org_controls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evidence_id", "org_control_id"),
    )
    op.create_index(
        op.f("ix_evidence_controls_evidence_id"), "evidence_controls", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_controls_org_control_id"),
        "evidence_controls",
        ["org_control_id"],
        unique=False,
    )
    op.create_table(
        "policy_acceptances",
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["policy_version_id"], ["policy_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_version_id", "user_id"),
    )
    op.create_index(
        op.f("ix_policy_acceptances_policy_version_id"),
        "policy_acceptances",
        ["policy_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_acceptances_user_id"), "policy_acceptances", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_acceptances_user_id"), table_name="policy_acceptances")
    op.drop_index(op.f("ix_policy_acceptances_policy_version_id"), table_name="policy_acceptances")
    op.drop_table("policy_acceptances")
    op.drop_index(op.f("ix_evidence_controls_org_control_id"), table_name="evidence_controls")
    op.drop_index(op.f("ix_evidence_controls_evidence_id"), table_name="evidence_controls")
    op.drop_table("evidence_controls")
    op.drop_index(op.f("ix_policy_versions_policy_id"), table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_policies_slug"), table_name="policies")
    op.drop_index(op.f("ix_policies_organization_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_evidence_organization_id"), table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
