"""phase 5b posture snapshots and connection monitoring

Revision ID: 15265e830082
Revises: bb92411c81dd
Create Date: 2026-06-21 01:22:15.037876
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15265e830082'
down_revision: str | None = 'bb92411c81dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posture_snapshots',
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('failing', sa.Integer(), nullable=False),
    sa.Column('not_assessed', sa.Integer(), nullable=False),
    sa.Column('percent_ready', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posture_snapshots_organization_id'), 'posture_snapshots', ['organization_id'], unique=False)
    op.add_column(
        'connections',
        sa.Column(
            'monitoring_enabled',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
    )
    op.add_column('connections', sa.Column('sync_interval_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'sync_interval_minutes')
    op.drop_column('connections', 'monitoring_enabled')
    op.drop_index(op.f('ix_posture_snapshots_organization_id'), table_name='posture_snapshots')
    op.drop_table('posture_snapshots')
    # ### end Alembic commands ###
