"""Phase 4 models

Revision ID: 81fea56d4013
Revises: 6d0add2b6668
Create Date: 2026-06-20 21:26:12.490814
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81fea56d4013"
down_revision: str | None = "6d0add2b6668"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("agent_key", sa.String(), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("running", "succeeded", "failed", name="airunstatus"), nullable=False
        ),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_runs_organization_id"), "ai_runs", ["organization_id"], unique=False
    )
    op.create_table(
        "notification_settings",
        sa.Column("slack_webhook_url", sa.String(), nullable=True),
        sa.Column("email_to", sa.String(), nullable=True),
        sa.Column("channels", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_settings_organization_id"),
        "notification_settings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("level", sa.Enum("info", "warning", name="notificationlevel"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    policyversionstatus = postgresql.ENUM("draft", "published", name="policyversionstatus")
    policyversionstatus.create(op.get_bind())
    op.add_column(
        "policy_versions",
        sa.Column(
            "status",
            sa.Enum("draft", "published", name="policyversionstatus"),
            server_default=sa.text("'published'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("policy_versions", "status")
    policyversionstatus = postgresql.ENUM("draft", "published", name="policyversionstatus")
    policyversionstatus.drop(op.get_bind())
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_settings_organization_id"), table_name="notification_settings"
    )
    op.drop_table("notification_settings")
    op.drop_index(op.f("ix_ai_runs_organization_id"), table_name="ai_runs")
    op.drop_table("ai_runs")
    # ### end Alembic commands ###
