"""phase 5c people access reviews training

Revision ID: 847f4e0eebf9
Revises: 15265e830082
Create Date: 2026-06-21 01:33:44.004757
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '847f4e0eebf9'
down_revision: str | None = '15265e830082'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_reviews',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'completed', name='access_review_status'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_reviews_organization_id'), 'access_reviews', ['organization_id'], unique=False)
    op.create_table('people',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'terminated', name='person_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    op.create_index(op.f('ix_people_organization_id'), 'people', ['organization_id'], unique=False)
    op.create_table('access_review_items',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('access_detail', sa.Text(), nullable=True),
    sa.Column('decision', sa.Enum('pending', 'keep', 'revoke', name='access_decision'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['access_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_review_items_organization_id'), 'access_review_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_access_review_items_review_id'), 'access_review_items', ['review_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('onboarding', 'offboarding', name='checklist_kind'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['done_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_organization_id'), 'checklist_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_checklist_items_person_id'), 'checklist_items', ['person_id'], unique=False)
    op.create_table('training_records',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_organization_id'), 'training_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_records_person_id'), 'training_records', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_records_person_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_organization_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_checklist_items_person_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_organization_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_access_review_items_review_id'), table_name='access_review_items')
    op.drop_index(op.f('ix_access_review_items_organization_id'), table_name='access_review_items')
    op.drop_table('access_review_items')
    op.drop_index(op.f('ix_people_organization_id'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_access_reviews_organization_id'), table_name='access_reviews')
    op.drop_table('access_reviews')
    # ### end Alembic commands ###
