"""templates

Revision ID: bb92411c81dd
Revises: 81fea56d4013
Create Date: 2026-06-20 21:59:08.359196
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

SANS_ACCESS_CONTROL_TEMPLATE = """# Access Control Policy

## 1.0 Purpose
The purpose of this policy is to establish the rules for the granting, control, monitoring, and removal of physical and logical access to Information Resources.

## 2.0 Scope
This policy applies to all personnel who have or are responsible for granting access to Information Resources.

## 3.0 Policy
### 3.1 Access Provisioning
- Access to Information Resources must be granted based on the principle of least privilege.
- Access requests must be documented and approved by the resource owner.

### 3.2 Authentication
- All user accounts must be secured with strong passwords.
- Multi-factor authentication (MFA) must be enabled for all remote access and administrative access.

### 3.3 Access Review and Revocation
- Access rights must be reviewed at regular intervals (e.g., quarterly).
- Access must be immediately revoked upon termination of employment or when no longer required.

## 4.0 Enforcement
Personnel found to have violated this policy may be subject to disciplinary action, up to and including termination of employment.
"""


# revision identifiers, used by Alembic.
revision: str = "bb92411c81dd"
down_revision: str | None = "81fea56d4013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_templates",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("type", sa.Enum("builtin", "custom", name="templatetype"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_templates_organization_id"),
        "policy_templates",
        ["organization_id"],
        unique=False,
    )
    op.add_column("policy_versions", sa.Column("source_template_id", sa.UUID(), nullable=True))
    op.add_column("policy_versions", sa.Column("source_evidence_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "policy_versions",
        "policy_templates",
        ["source_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "policy_versions", "evidence", ["source_evidence_id"], ["id"], ondelete="SET NULL"
    )

    # Seed built-in templates
    op.execute(f"""
        INSERT INTO policy_templates (id, name, description, body, type, organization_id, created_at, updated_at)
        VALUES (
            gen_random_uuid(), 
            'SANS Access Control Policy', 
            'Industry standard access management policy based on SANS Institute guidelines.', 
            '{SANS_ACCESS_CONTROL_TEMPLATE.replace("'", "''")}', 
            'builtin', 
            NULL, 
            now(), 
            now()
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "policy_versions", type_="foreignkey")
    op.drop_constraint(None, "policy_versions", type_="foreignkey")
    op.drop_column("policy_versions", "source_evidence_id")
    op.drop_column("policy_versions", "source_template_id")
    op.drop_index(op.f("ix_policy_templates_organization_id"), table_name="policy_templates")
    op.drop_table("policy_templates")
    # ### end Alembic commands ###
